version: "3.9"  # optional since v1.27.0
services:
  docs_ms:
    container_name: firma_docs_ms   
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8091:3000

