FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
RUN yarn install

# Install TS
COPY tsconfig.json ./
RUN yarn global add typescript

RUN yarn

# Set the server port
ENV PORT=8091
EXPOSE 8091

ENTRYPOINT [ "yarn", "run" ]

